---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./audiobookshelf/ks.yaml
  - ./jellyfin/ks.yaml
  - ./komga/ks.yaml
  - ./ombi/ks.yaml
  - ./overseerr/ks.yaml
  - ./tautulli/ks.yaml
  - ./tdarr/ks.yaml
